name: OCMFixer
main: me.rayzr522.ocmfixer.OCMFixerPlugin
version: ${project.version}
description: Reads playerdata files and fixes the attack speed
commands:
  read:
    description: Reads a world folder
    usage: "\u00a7cUsage: /read <world>"
